### PR TITLE
TAF Functionality

### PR DESCRIPTION
**Pull request by njtrettel**
Hey there.

I wanted to make a METARMap myself, but thought it would be really cool to also have the ability to forecast the weather as well. So I did just that.

It uses a sliding potentiometer to adjust the displaying time; all the way left is current time (showing METARs), and then sliding it right it increases hour by hour until all the way right, which is +23 hours. This means I needed to set up some sort of event loop to determine when the slider changes, and adjust the lights accordingly. That was quite a big change, given that the existing setup runs the script once every 5 minutes and quits. _I noticed since I made these changes, you've added a loop to handle the blinking and screen output, but I still would've needed a new event loop regardless_. 

Unfortunately I think my fork differs too much from this repo to actually be merged in; I pretty much left all of your code alone and added a `loop.py` script for my new METAR/TAF map. So the result is multiple entry points and it's probably quite confusing to someone unfamiliar. But I still wanted to open this PR and share my version (and also say thanks for writing this repo in the first place!). I tried to make the diff nice and clear, and added a separate README in case you do want these changes. I'll just leave this here and let you do with it what you will ¯\_(ツ)_/¯

Below is a more detailed description of the changes and a few videos of how it looks (it's not finished yet...)

<details><summary><strong>Detailed description</strong> (from <a href="https://github.com/njtrettel/METARMap/pull/1#issue-533107115">here</a>)</summary>

## Background
First let's talk about the existing implementation, which will help explain why I was not able to add this functionality on top of it.

### Existing implementation
The `metar.py` script handles fetching the METAR data and setting the lights appropriately. It's a one-and-done script; once it finishes updating the lights, it exits. To get it to update on a regular interval, you must use `cron`, which will simply run the script over and over on the provided interval.

### Desired implementation
Imagine the finished product. I wanted the ability to add a little slider bar at the bottom of the map which, when slid to the right, switches from displaying observed weather (METARs) to forecast weather (TAFs). Then I'd want some little screen as well to show exactly for what time I'm forecasting.

_With the simplistic one-and-done script implementation, it would be quite ugly to add the ability to listen for a change to the slider and then run the script to update the lights. The best way I could think of doing this while still keeping the one-and-done script approach is to keep one running process to listen for the slider, and then use a subprocess to exec the `metar.py` script (via bash) when the value is changed. The `metar.py` script would then re-obtain the slider value and update the lights accordingly. That's already too ugly for my liking since two separate process need to know the value of the slider. Then comes the problem... how does the `metar.py` script know the weather data without re-fetching it on every slider change? You'd have to store that in a file... So, no thanks._

## The solution

Essentially, it boils down to the fact that I need one infinitely running process to handle everything. The process needs to be async, otherwise I'd have to carefully manage when to re-fetch data without holding up the slider listener.

The infinitely running process lives in `loop.py`. It uses an `asyncio` event loop to handle task scheduling. It starts by immediately scheduling the weather data fetcher, and then immediately scheduling the slider listener:
1. The weather data fetcher fetches (obvi) and stores the METAR and TAF data into a dictionary in memory. Then it recursively reschedules itself `REFRESH_RATE_FETCH` seconds later.
1. The slider listener checks to see if the slider value is different than the one stored in memory. If so, it immediately schedules the light changing function. Then it recursively reschedules itself `REFRESH_RATE_SLIDER` seconds later
   1. The light changing function looks at the slider value and METAR and TAF dictionary and sets the lights based on the weather data (uses the TAF if the slider value is looking into the future)

Now the map no longer relies on a `cron` job to periodically run a script and exit. Instead, the infinitely running process can update the weather data itself periodically, and can see slider value to act accordingly.

**This means that the `metar.py`, `crontab`, and `refresh.sh` are not used in this implementation**

### Required changes

All of that stuff mentioned above required numerous changes:
1. adds support for a 3.3v Analog to Digital Converter (ADC)
   - the ADC is connected to the Raspberry Pi's I2C bus
   - the ADC is receiving input from a 3.3v potentiometer
1. adds support for a 3.3v OLED screen
   - the OLED screen is also connected to the Raspberry Pi's I2C bus
1. implement an `asyncio` event loop to listen for changes to the potentiometer and act accordingly
1. implement the ability to generate a flight category forecast for a given taf

</details>

<details><summary>What it looks like (it's not done...)</summary>

screen

PXL_20201214_183532720

I hollowed out the bottom piece of the frame and will eventually mount the screen and slider into it.

There is one somewhat big downside though: not every airport with a METAR necessarily has a TAF. If you're in an area with busy airspace, there's a better bet more airports will have TAFs. 

</details>

### CODE REVIEW

**Comment by proppilot** [comment]
Some nice functionality with your forked version.  I ended up creating my own version that runs continuously so that I can use a flush mounted PIR motion detector on the map that senses movement in the room and triggers the LEDs on for an additional 30 minutes after no further movement detected.  The LEDs have a finite life that if left on 24/7 will only be a few years which is not long considering the work to replace one/many.

**Comment by njtrettel** [comment]
That's a neat idea. Might need to do that with mine in the future

**Comment by lostlocalhost** [comment]
> Some nice functionality with your forked version. I ended up creating my own version that runs continuously so that I can use a flush mounted PIR motion detector on the map that senses movement in the room and triggers the LEDs on for an additional 30 minutes after no further movement detected. The LEDs have a finite life that if left on 24/7 will only be a few years which is not long considering the work to replace one/many.

Great idea! I have an extra laying around from a different proj, I'll have to do this... Mind pushing your code up to share?

**Comment by proppilot** [comment]
[MetarMaps.zip](https://github.com/prueker/METARMap/files/5963903/MetarMaps.zip)

Here is my code set.  There is also code for the shutdown/reset button I installed in the map frame and to drive the OLED display that is embedded but I have only showing my home field CYKF

**Comment by prueker** [comment]
It's a neat addition, but I think for most people, they are happy with just showing the METAR functionality, so I want to keep the main repo copy simple with just that.

**Pull request closed without merging**
