### PR TITLE
Add VT sequences to display the printed flight category in the same color as the airport's LED.

### PR DESCRIPTION
**Pull request by BrentRector**

### CODE REVIEW

**Comment by prueker** [comment]
It's an interesting idea, the only problem is that most terminals don't run with truecolor and thus it won't actually do anything.

The print message is really more for testing than for the continuous running of the script since most people only care about the LED output and not what's printed in the console.

**Comment by BrentRector** [comment]
The Windows terminal supports truecolor and the WSL subsystem on Windows as well. I've no idea of Macs. Microsoft docs mention that most Linux systems support truecolor.

I'm still waiting on my LEDs (going with a significantly different approach hardware-wise as I'm getting discrete addressable LEDs). So I did this to occupy the down time. Thought I'd submit it in case anyone was interested. And if it doesn't do anything on some systems, no harm, no foul. :)

**Comment by prueker** [comment]
Most linux terminals are running on 8 or 256 colors. I tried your code using Putty into the Raspberry Pi and it basically just does nothing since the default is xterm, which runs on 8 colors.
Since most people are building this on a Raspberry Pi, I'm not sure if it adds much value since it's effectively unused code.

What different hardware approach are you going with?
The WS8211 LEDs are individually addressable, but linked in a chain so it's simple to connect, which is the whole point of the project.

**Comment by BrentRector** [comment]
Interesting. I just use the Windows built-in SSH from a Windows Terminal into my Raspberry Pi and I get 24-bit color. Likely it’s the Windows Terminal doing the heavy lifting. I’ve not tried it from a console on the Pi itself. I am building it on a Pi but from a Windows Terminal using SSH.

I’m planning to use NeoPixel Mini 3535 RGB LEDs, which are WS8211 compatible but fixed at 800 Khz, and come as individual 3mm parts. My idea is to mount the map on a thin opaque backing surface, put in a picture frame with an acrylic, not glass cover. Then drill 3 mm holes thru the acrylic at each airport. Insert and fix 3 mm light pipes into the holes. Then mount each 3 mm LED on the rear with the light coming thru the light pipe. The trick will be wiring up such small devices. One I get it wired, hopefully, it’ll work just as your existing solution but using much smaller LEDs.
[A close up of a coin  Description automatically generated]

              Brent

**Comment by prueker** [comment]
Yes that makes sense.  I'll close the PR since I think it won't be useful for the majority of people.

Good luck with your project, sounds like a cool idea with those tiny LEDs.

**Pull request closed without merging**
