### PR TITLE
Add Dim Offset Time

### PR DESCRIPTION
**Pull request by nesincg**
Add a variable to change the amount of time after sunrise and the amount of time before sunset that the lights change brightness. IOW. At sunrise, it's still pretty dark, so leave it dim for DIM_OFFSET_TIME.

### CODE REVIEW

**Comment by lynolamero** [comment]
pi@METAR-MAP:~ $ sudo python3 metar.py
Running metar.py at 31/01/2022 15:00
LocationInfo(name='Seattle', region='USA', timezone='US/Pacific', latitude=47.6, longitude=-122.31666666666666)
Need some help with this one:

Traceback (most recent call last):
  File "metar.py", line 83, in <module>
    ast = astral.Astral()
AttributeError: module 'astral' has no attribute 'Astral'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "metar.py", line 105, in <module>
    BRIGHT_TIME_START = (sun['sunrise'] + timedelta(minutes=DIM_OFFSET_TIME)).time()
NameError: name 'timedelta' is not defined

Any help would be appreciated.  Thanks!

**Comment by lynolamero** [comment]
Need some help with this one:

pi@METAR-MAP:~ $ sudo python3 metar.py
Running metar.py at 31/01/2022 15:00
LocationInfo(name='Seattle', region='USA', timezone='US/Pacific', latitude=47.6, longitude=-122.31666666666666)

Traceback (most recent call last):
File "metar.py", line 83, in
ast = astral.Astral()
AttributeError: module 'astral' has no attribute 'Astral'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "metar.py", line 105, in
BRIGHT_TIME_START = (sun['sunrise'] + timedelta(minutes=DIM_OFFSET_TIME)).time()
NameError: name 'timedelta' is not defined

-----astral was loaded already--------
Requirement already satisfied: astral in /usr/local/lib/python3.7/dist-packages (2.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from astral) (2020.4)

Any help would be appreciated. Thanks!

**Comment by nesincg** [comment]
Crap. I forgot this in the top just under import datetime

from datetime import timedelta

**Comment by lynolamero** [comment]
Updated as described.  Works well.  Thanks Chris

**Comment by funk74** [comment]
Anyone know how to make the lights dim based on each airports sunset time?

**Pull request closed without merging**
